### ISSUE TITLE
嵌套在NestedScrollView里，界面不显示数据

### ISSUE THREAD

**Issue by fhdis** [jeanboydev/Android-RecyclerViewHelper#1]
嵌套在NestedScrollView里，界面不显示数据。打日志看，adapter的方法基本都走了
嵌套在ScrollView里面，一直显示正在加载数据。没办法继续加载数据

**Comment by jeanboydev** [comment]
@fhdis 
在NestedScrollView/ScrollView里面嵌套，需要处理滑动冲突和动态计算view高度。
